### ISSUE TITLE
improvement: add logic to avoid overwriting owner.txt

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks-Workflows/nf-synindex#15]
Currently, this workflow will (probably?) overwrite an owner.txt file with the account that is doing the indexing. This might not be desirable when indexing non-tower buckets that might have several owners in the owner.txt file. It would be good if this step was a bit more sophisticated - e.g. if owner.txt exists and does not list indexing_account, it should add the indexing account principal id. If it does not exist then it can proceed as usual.

**Comment by BWMac** [comment]
We are deprecating this repository and instead maintaining its functionality in [nf-synapse](https://github.com/Sage-Bionetworks-Workflows/nf-synapse). This issue is tracked in Jira [here](https://sagebionetworks.jira.com/browse/IBCDPE-693).
