### ISSUE TITLE
improvement: skip files that are already indexed

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks-Workflows/nf-synindex#16]
If you are running this workflow on a bucket that has already been partially indexed (say, for example, someone shares 100 files, this is indexed, and then a few months later another 100 files are added and the indexing needs to be repeated), the workflow should skip files that already exist in the in the destination parent ID on synapse. For small datasets this is probably not so important, but could reduce expenses significantly with large datasets: 

<img width="582" alt="Screen Shot 2023-09-20 at 8 58 07 AM" src="https://github.com/Sage-Bionetworks-Workflows/nf-synindex/assets/20408008/02bf443b-68c3-400b-b891-998f371d6b8e">

In this example, about 1/3 of the data were already indexed, so skipping those would probably have made this workflow about 1/3 cheaper. I anticipate having to re-index this bucket one or two more times in the future, and in that case would save ~$400 per run if the current files were skipped.

**Comment by BWMac** [comment]
We are deprecating this repository and instead maintaining its functionality in [nf-synapse](https://github.com/Sage-Bionetworks-Workflows/nf-synapse). This issue is tracked in Jira [here](https://sagebionetworks.jira.com/browse/IBCDPE-692).
