### ISSUE TITLE
Should there be a conditional if the s3 bucket is already registered to Synapse

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks-Workflows/nf-synindex#2]
Currently, it looks like the pipeline always registers the s3 bucket, should this step be skipped if the bucket is already registered to Synapse.

**Comment by BrunoGrandePhD** [comment]
I opted against this approach because of the following behavior with the `POST /storageLocation` endpoint ([source](https://rest-docs.synapse.org/rest/POST/storageLocation.html)): 

> The creation of a storage location is idempotent for the user: if the same user requests the creation of a storage location that already exists with the same properties the previous storage location will be returned.

**Comment by thomasyu888** [comment]
Thanks Bruno - I was unaware of this.
